echo "First number is $num1=5" 
echo "Second number is $num2=12" 
echo "Addition of both the numbers is : $((num1 + num2))"
echo "This script will now be pulled from webhook" 
echo " New changes added" 
